// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

#[allow(unused_imports)]
use crate::auto::*;

#[doc(alias = "WpObjectFeatures")]
pub type ObjectFeatures = u32;
