// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::{ffi,GlobalProxy,Object,PipewireObject,Properties,Proxy};
use glib::{translate::*};

glib::wrapper! {
    #[doc(alias = "WpClient")]
    pub struct Client(Object<ffi::WpClient, ffi::WpClientClass>) @extends GlobalProxy, Proxy, Object, @implements PipewireObject;

    match fn {
        type_ => || ffi::wp_client_get_type(),
    }
}

impl Client {
    #[doc(alias = "wp_client_send_error")]
    pub fn send_error(&self, id: u32, res: i32, message: &str) {
        unsafe {
            ffi::wp_client_send_error(self.to_glib_none().0, id, res, message.to_glib_none().0);
        }
    }

    //#[doc(alias = "wp_client_update_permissions")]
    //pub fn update_permissions(&self, n_perm: u32, : /*Unknown conversion*//*Unimplemented*/Basic: VarArgs) {
    //    unsafe { TODO: call ffi:wp_client_update_permissions() }
    //}

    //#[doc(alias = "wp_client_update_permissions_array")]
    //pub fn update_permissions_array(&self, permissions: /*Unimplemented*/&CArray TypeId { ns_id: 0, id: 0 }) {
    //    unsafe { TODO: call ffi:wp_client_update_permissions_array() }
    //}

    #[doc(alias = "wp_client_update_properties")]
    pub fn update_properties(&self, updates: Properties) {
        unsafe {
            ffi::wp_client_update_properties(self.to_glib_none().0, updates.into_glib_ptr());
        }
    }
}
