// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::{ffi};
use glib::{prelude::*};

glib::wrapper! {
    #[doc(alias = "WpComponentLoader")]
    pub struct ComponentLoader(Interface<ffi::WpComponentLoader, ffi::WpComponentLoaderInterface>);

    match fn {
        type_ => || ffi::wp_component_loader_get_type(),
    }
}

impl ComponentLoader {
        pub const NONE: Option<&'static ComponentLoader> = None;
    
}

pub trait ComponentLoaderExt: IsA<ComponentLoader> + 'static {}

impl<O: IsA<ComponentLoader>> ComponentLoaderExt for O {}
