// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::{ffi,Event,EventDispatcher};
use glib::{prelude::*,signal::{connect_raw, SignalHandlerId},translate::*};
use std::{boxed::Box as Box_};

glib::wrapper! {
    #[doc(alias = "WpEventHook")]
    pub struct EventHook(Object<ffi::WpEventHook, ffi::WpEventHookClass>);

    match fn {
        type_ => || ffi::wp_event_hook_get_type(),
    }
}

impl EventHook {
        pub const NONE: Option<&'static EventHook> = None;
    
}

pub trait EventHookExt: IsA<EventHook> + 'static {
    #[doc(alias = "wp_event_hook_finish")]
    fn finish(&self, res: &impl IsA<gio::AsyncResult>) -> Result<(), glib::Error> {
        unsafe {
            let mut error = std::ptr::null_mut();
            let is_ok = ffi::wp_event_hook_finish(self.as_ref().to_glib_none().0, res.as_ref().to_glib_none().0, &mut error);
            debug_assert_eq!(is_ok == glib::ffi::GFALSE, !error.is_null());
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }

    #[doc(alias = "wp_event_hook_get_dispatcher")]
    #[doc(alias = "get_dispatcher")]
    fn dispatcher(&self) -> Option<EventDispatcher> {
        unsafe {
            from_glib_full(ffi::wp_event_hook_get_dispatcher(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "wp_event_hook_get_name")]
    #[doc(alias = "get_name")]
    fn name(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::wp_event_hook_get_name(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "wp_event_hook_get_runs_after_hooks")]
    #[doc(alias = "get_runs_after_hooks")]
    #[doc(alias = "runs-after-hooks")]
    fn runs_after_hooks(&self) -> Vec<glib::GString> {
        unsafe {
            FromGlibPtrContainer::from_glib_none(ffi::wp_event_hook_get_runs_after_hooks(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "wp_event_hook_get_runs_before_hooks")]
    #[doc(alias = "get_runs_before_hooks")]
    #[doc(alias = "runs-before-hooks")]
    fn runs_before_hooks(&self) -> Vec<glib::GString> {
        unsafe {
            FromGlibPtrContainer::from_glib_none(ffi::wp_event_hook_get_runs_before_hooks(self.as_ref().to_glib_none().0))
        }
    }

    //#[doc(alias = "wp_event_hook_run")]
    //fn run<P: FnOnce(Result<(), glib::Error>) + 'static>(&self, event: &Event, cancellable: Option<&impl IsA<gio::Cancellable>>, callback: P) {
    //    unsafe { TODO: call ffi:wp_event_hook_run() }
    //}

    #[doc(alias = "wp_event_hook_runs_for_event")]
    fn runs_for_event(&self, event: &Event) -> bool {
        unsafe {
            from_glib(ffi::wp_event_hook_runs_for_event(self.as_ref().to_glib_none().0, event.to_glib_none().0))
        }
    }

    #[doc(alias = "wp_event_hook_set_dispatcher")]
    fn set_dispatcher(&self, dispatcher: &EventDispatcher) {
        unsafe {
            ffi::wp_event_hook_set_dispatcher(self.as_ref().to_glib_none().0, dispatcher.to_glib_none().0);
        }
    }

    #[doc(alias = "dispatcher")]
    fn connect_dispatcher_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_dispatcher_trampoline<P: IsA<EventHook>, F: Fn(&P) + 'static>(this: *mut ffi::WpEventHook, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(EventHook::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::dispatcher".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_dispatcher_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }
}

impl<O: IsA<EventHook>> EventHookExt for O {}
