// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::{ffi,Core,Event,EventHook,Iterator};
use glib::{prelude::*,translate::*};

glib::wrapper! {
    #[doc(alias = "WpEventDispatcher")]
    pub struct EventDispatcher(Object<ffi::WpEventDispatcher, ffi::WpEventDispatcherClass>);

    match fn {
        type_ => || ffi::wp_event_dispatcher_get_type(),
    }
}

impl EventDispatcher {
    #[doc(alias = "wp_event_dispatcher_new_hooks_iterator")]
    pub fn new_hooks_iterator(&self) -> Option<Iterator> {
        unsafe {
            from_glib_full(ffi::wp_event_dispatcher_new_hooks_iterator(self.to_glib_none().0))
        }
    }

    #[doc(alias = "wp_event_dispatcher_push_event")]
    pub fn push_event(&self, event: Event) {
        unsafe {
            ffi::wp_event_dispatcher_push_event(self.to_glib_none().0, event.into_glib_ptr());
        }
    }

    #[doc(alias = "wp_event_dispatcher_register_hook")]
    pub fn register_hook(&self, hook: &impl IsA<EventHook>) {
        unsafe {
            ffi::wp_event_dispatcher_register_hook(self.to_glib_none().0, hook.as_ref().to_glib_none().0);
        }
    }

    #[doc(alias = "wp_event_dispatcher_unregister_hook")]
    pub fn unregister_hook(&self, hook: &impl IsA<EventHook>) {
        unsafe {
            ffi::wp_event_dispatcher_unregister_hook(self.to_glib_none().0, hook.as_ref().to_glib_none().0);
        }
    }

    #[doc(alias = "wp_event_dispatcher_get_instance")]
    #[doc(alias = "get_instance")]
    pub fn instance(core: &Core) -> Option<EventDispatcher> {
        skip_assert_initialized!();
        unsafe {
            from_glib_full(ffi::wp_event_dispatcher_get_instance(core.to_glib_none().0))
        }
    }
}
