// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::{ffi,EventDispatcher,Iterator,Properties};
use glib::{prelude::*,translate::*};

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct Event(Shared<ffi::WpEvent>);

    match fn {
        ref => |ptr| ffi::wp_event_ref(ptr),
        unref => |ptr| ffi::wp_event_unref(ptr),
        type_ => || ffi::wp_event_get_type(),
    }
}

impl Event {
    #[doc(alias = "wp_event_new")]
    pub fn new(type_: &str, priority: i32, properties: Option<Properties>, source: &impl IsA<glib::Object>, subject: Option<&impl IsA<glib::Object>>) -> Event {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::wp_event_new(type_.to_glib_none().0, priority, properties.into_glib_ptr(), source.as_ref().to_glib_none().0, subject.map(|p| p.as_ref()).to_glib_none().0))
        }
    }

    #[doc(alias = "wp_event_collect_hooks")]
    pub fn collect_hooks(&self, dispatcher: &EventDispatcher) -> bool {
        unsafe {
            from_glib(ffi::wp_event_collect_hooks(self.to_glib_none().0, dispatcher.to_glib_none().0))
        }
    }

    #[doc(alias = "wp_event_get_cancellable")]
    #[doc(alias = "get_cancellable")]
    pub fn cancellable(&self) -> Option<gio::Cancellable> {
        unsafe {
            from_glib_none(ffi::wp_event_get_cancellable(self.to_glib_none().0))
        }
    }

    #[doc(alias = "wp_event_get_data")]
    #[doc(alias = "get_data")]
    pub fn data(&self, key: &str) -> Option<glib::Value> {
        unsafe {
            from_glib_none(ffi::wp_event_get_data(self.to_glib_none().0, key.to_glib_none().0))
        }
    }

    #[doc(alias = "wp_event_get_name")]
    #[doc(alias = "get_name")]
    pub fn name(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::wp_event_get_name(self.to_glib_none().0))
        }
    }

    #[doc(alias = "wp_event_get_priority")]
    #[doc(alias = "get_priority")]
    pub fn priority(&self) -> i32 {
        unsafe {
            ffi::wp_event_get_priority(self.to_glib_none().0)
        }
    }

    #[doc(alias = "wp_event_get_properties")]
    #[doc(alias = "get_properties")]
    pub fn properties(&self) -> Option<Properties> {
        unsafe {
            from_glib_full(ffi::wp_event_get_properties(self.to_glib_none().0))
        }
    }

    #[doc(alias = "wp_event_get_source")]
    #[doc(alias = "get_source")]
    pub fn source(&self) -> Option<glib::Object> {
        unsafe {
            from_glib_full(ffi::wp_event_get_source(self.to_glib_none().0))
        }
    }

    #[doc(alias = "wp_event_get_subject")]
    #[doc(alias = "get_subject")]
    pub fn subject(&self) -> Option<glib::Object> {
        unsafe {
            from_glib_full(ffi::wp_event_get_subject(self.to_glib_none().0))
        }
    }

    #[doc(alias = "wp_event_new_hooks_iterator")]
    pub fn new_hooks_iterator(&self) -> Option<Iterator> {
        unsafe {
            from_glib_full(ffi::wp_event_new_hooks_iterator(self.to_glib_none().0))
        }
    }

    #[doc(alias = "wp_event_set_data")]
    pub fn set_data(&self, key: &str, data: Option<&glib::Value>) {
        unsafe {
            ffi::wp_event_set_data(self.to_glib_none().0, key.to_glib_none().0, data.to_glib_none().0);
        }
    }

    #[doc(alias = "wp_event_stop_processing")]
    pub fn stop_processing(&self) {
        unsafe {
            ffi::wp_event_stop_processing(self.to_glib_none().0);
        }
    }
}
