// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::{ffi,GlobalProxy,Object,PipewireObject,Proxy};

glib::wrapper! {
    #[doc(alias = "WpFactory")]
    pub struct Factory(Object<ffi::WpFactory, ffi::WpFactoryClass>) @extends GlobalProxy, Proxy, Object, @implements PipewireObject;

    match fn {
        type_ => || ffi::wp_factory_get_type(),
    }
}

impl Factory {}
