// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::{ffi};
use glib::{translate::*};

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct Iterator(Shared<ffi::WpIterator>);

    match fn {
        ref => |ptr| ffi::wp_iterator_ref(ptr),
        unref => |ptr| ffi::wp_iterator_unref(ptr),
        type_ => || ffi::wp_iterator_get_type(),
    }
}

impl Iterator {
    //#[doc(alias = "wp_iterator_new")]
    //pub fn new(methods: /*Ignored*/&IteratorMethods, user_size: usize) -> Iterator {
    //    unsafe { TODO: call ffi:wp_iterator_new() }
    //}

    //#[doc(alias = "wp_iterator_new_ptr_array")]
    //pub fn new_ptr_array(items: /*Unimplemented*/Vec<Basic: Pointer>, item_type: glib::types::Type) -> Iterator {
    //    unsafe { TODO: call ffi:wp_iterator_new_ptr_array() }
    //}

    //#[doc(alias = "wp_iterator_fold")]
    //pub fn fold<P: FnMut(&glib::Value, &glib::Value) -> bool>(&self, func: P, ret: /*Unimplemented*/glib::Value) -> bool {
    //    unsafe { TODO: call ffi:wp_iterator_fold() }
    //}

    #[doc(alias = "wp_iterator_foreach")]
    pub fn foreach<P: FnMut(&glib::Value)>(&self, func: P) -> bool {
        let mut func_data: P = func;
        unsafe extern "C" fn func_func<P: FnMut(&glib::Value)>(item: *const glib::gobject_ffi::GValue, data: glib::ffi::gpointer) {
            let item = from_glib_borrow(item);
            let callback = data as *mut P;
            (*callback)(&item)
        }
        let func = Some(func_func::<P> as _);
        let super_callback0: &mut P = &mut func_data;
        unsafe {
            from_glib(ffi::wp_iterator_foreach(self.to_glib_none().0, func, super_callback0 as *mut _ as *mut _))
        }
    }

    //#[doc(alias = "wp_iterator_get_user_data")]
    //#[doc(alias = "get_user_data")]
    //pub fn user_data(&self) -> /*Unimplemented*/Option<Basic: Pointer> {
    //    unsafe { TODO: call ffi:wp_iterator_get_user_data() }
    //}

    #[doc(alias = "wp_iterator_next")]
    pub fn next(&self) -> Option<glib::Value> {
        unsafe {
            let mut item = glib::Value::uninitialized();
            let ret = from_glib(ffi::wp_iterator_next(self.to_glib_none().0, item.to_glib_none_mut().0));
            if ret { Some(item) } else { None }
        }
    }

    #[doc(alias = "wp_iterator_reset")]
    pub fn reset(&self) {
        unsafe {
            ffi::wp_iterator_reset(self.to_glib_none().0);
        }
    }
}
