// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::{ffi};
use glib::{translate::*};

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct MetadataItem(Shared<ffi::WpMetadataItem>);

    match fn {
        ref => |ptr| ffi::wp_metadata_item_ref(ptr),
        unref => |ptr| ffi::wp_metadata_item_unref(ptr),
        type_ => || ffi::wp_metadata_item_get_type(),
    }
}

impl MetadataItem {
    #[doc(alias = "wp_metadata_item_get_key")]
    #[doc(alias = "get_key")]
    pub fn key(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::wp_metadata_item_get_key(self.to_glib_none().0))
        }
    }

    #[doc(alias = "wp_metadata_item_get_subject")]
    #[doc(alias = "get_subject")]
    pub fn subject(&self) -> u32 {
        unsafe {
            ffi::wp_metadata_item_get_subject(self.to_glib_none().0)
        }
    }

    #[doc(alias = "wp_metadata_item_get_value")]
    #[doc(alias = "get_value")]
    pub fn value(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::wp_metadata_item_get_value(self.to_glib_none().0))
        }
    }

    #[doc(alias = "wp_metadata_item_get_value_type")]
    #[doc(alias = "get_value_type")]
    pub fn value_type(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::wp_metadata_item_get_value_type(self.to_glib_none().0))
        }
    }
}
