// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::{ffi,Iterator,Object,Properties,Proxy};
use glib::{object::ObjectType as _,prelude::*,signal::{connect_raw, SignalHandlerId},translate::*};
use std::{boxed::Box as Box_};

glib::wrapper! {
    #[doc(alias = "WpPipewireObject")]
    pub struct PipewireObject(Interface<ffi::WpPipewireObject, ffi::WpPipewireObjectInterface>) @requires Proxy, Object;

    match fn {
        type_ => || ffi::wp_pipewire_object_get_type(),
    }
}

impl PipewireObject {
        pub const NONE: Option<&'static PipewireObject> = None;
    
}

pub trait PipewireObjectExt: IsA<PipewireObject> + 'static {
    //#[doc(alias = "wp_pipewire_object_enum_params")]
    //fn enum_params<P: FnOnce(Result<Option<Iterator>, glib::Error>) + 'static>(&self, id: Option<&str>, filter: /*Ignored*/Option<&SpaPod>, cancellable: Option<&impl IsA<gio::Cancellable>>, callback: P) {
    //    unsafe { TODO: call ffi:wp_pipewire_object_enum_params() }
    //}

    //
    //fn enum_params_future(&self, id: Option<&str>, filter: /*Ignored*/Option<&SpaPod>) -> Pin<Box_<dyn std::future::Future<Output = Result<Option<Iterator>, glib::Error>> + 'static>> {

        //let id = id.map(ToOwned::to_owned);
        //let filter = filter.map(ToOwned::to_owned);
        //Box_::pin(gio::GioFuture::new(self, move |obj, cancellable, send| {
        //    obj.enum_params(
        //        id.as_ref().map(::std::borrow::Borrow::borrow),
        //        filter.as_ref().map(::std::borrow::Borrow::borrow),
        //        Some(cancellable),
        //        move |res| {
        //            send.resolve(res);
        //        },
        //    );
        //}))
    //}

    //#[doc(alias = "wp_pipewire_object_enum_params_sync")]
    //fn enum_params_sync(&self, id: &str, filter: /*Ignored*/Option<&SpaPod>) -> Option<Iterator> {
    //    unsafe { TODO: call ffi:wp_pipewire_object_enum_params_sync() }
    //}

    //#[doc(alias = "wp_pipewire_object_get_native_info")]
    //#[doc(alias = "get_native_info")]
    //#[doc(alias = "native-info")]
    //fn native_info(&self) -> /*Unimplemented*/Option<Basic: Pointer> {
    //    unsafe { TODO: call ffi:wp_pipewire_object_get_native_info() }
    //}

    #[doc(alias = "wp_pipewire_object_get_param_info")]
    #[doc(alias = "get_param_info")]
    #[doc(alias = "param-info")]
    fn param_info(&self) -> Option<glib::Variant> {
        unsafe {
            from_glib_full(ffi::wp_pipewire_object_get_param_info(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "wp_pipewire_object_get_properties")]
    #[doc(alias = "get_properties")]
    fn properties(&self) -> Option<Properties> {
        unsafe {
            from_glib_full(ffi::wp_pipewire_object_get_properties(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "wp_pipewire_object_get_property")]
    #[doc(alias = "get_property")]
    fn property(&self, key: &str) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::wp_pipewire_object_get_property(self.as_ref().to_glib_none().0, key.to_glib_none().0))
        }
    }

    #[doc(alias = "wp_pipewire_object_new_properties_iterator")]
    fn new_properties_iterator(&self) -> Option<Iterator> {
        unsafe {
            from_glib_full(ffi::wp_pipewire_object_new_properties_iterator(self.as_ref().to_glib_none().0))
        }
    }

    //#[doc(alias = "wp_pipewire_object_set_param")]
    //fn set_param(&self, id: &str, flags: u32, param: /*Ignored*/SpaPod) -> bool {
    //    unsafe { TODO: call ffi:wp_pipewire_object_set_param() }
    //}

    #[doc(alias = "params-changed")]
    fn connect_params_changed<F: Fn(&Self, &str) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn params_changed_trampoline<P: IsA<PipewireObject>, F: Fn(&P, &str) + 'static>(this: *mut ffi::WpPipewireObject, object: *mut std::ffi::c_char, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(PipewireObject::from_glib_borrow(this).unsafe_cast_ref(), &glib::GString::from_glib_borrow(object))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"params-changed".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(params_changed_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "native-info")]
    fn connect_native_info_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_native_info_trampoline<P: IsA<PipewireObject>, F: Fn(&P) + 'static>(this: *mut ffi::WpPipewireObject, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(PipewireObject::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::native-info".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_native_info_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "param-info")]
    fn connect_param_info_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_param_info_trampoline<P: IsA<PipewireObject>, F: Fn(&P) + 'static>(this: *mut ffi::WpPipewireObject, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(PipewireObject::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::param-info".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_param_info_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "properties")]
    fn connect_properties_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_properties_trampoline<P: IsA<PipewireObject>, F: Fn(&P) + 'static>(this: *mut ffi::WpPipewireObject, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(PipewireObject::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::properties".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_properties_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }
}

impl<O: IsA<PipewireObject>> PipewireObjectExt for O {}
