// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::{ffi};
use glib::{translate::*};

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct ProcInfo(Shared<ffi::WpProcInfo>);

    match fn {
        ref => |ptr| ffi::wp_proc_info_ref(ptr),
        unref => |ptr| ffi::wp_proc_info_unref(ptr),
        type_ => || ffi::wp_proc_info_get_type(),
    }
}

impl ProcInfo {
    #[doc(alias = "wp_proc_info_get_arg")]
    #[doc(alias = "get_arg")]
    pub fn arg(&self, index: u32) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::wp_proc_info_get_arg(self.to_glib_none().0, index))
        }
    }

    #[doc(alias = "wp_proc_info_get_cgroup")]
    #[doc(alias = "get_cgroup")]
    pub fn cgroup(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::wp_proc_info_get_cgroup(self.to_glib_none().0))
        }
    }

    #[doc(alias = "wp_proc_info_get_n_args")]
    #[doc(alias = "get_n_args")]
    pub fn n_args(&self) -> u32 {
        unsafe {
            ffi::wp_proc_info_get_n_args(self.to_glib_none().0)
        }
    }

    #[doc(alias = "wp_proc_info_get_parent_pid")]
    #[doc(alias = "get_parent_pid")]
    pub fn parent_pid(&self) -> libc::pid_t {
        unsafe {
            ffi::wp_proc_info_get_parent_pid(self.to_glib_none().0)
        }
    }

    #[doc(alias = "wp_proc_info_get_pid")]
    #[doc(alias = "get_pid")]
    pub fn pid(&self) -> libc::pid_t {
        unsafe {
            ffi::wp_proc_info_get_pid(self.to_glib_none().0)
        }
    }
}
