// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::{ffi,SettingsSpecType};
use glib::{translate::*};

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct SettingsSpec(Shared<ffi::WpSettingsSpec>);

    match fn {
        ref => |ptr| ffi::wp_settings_spec_ref(ptr),
        unref => |ptr| ffi::wp_settings_spec_unref(ptr),
        type_ => || ffi::wp_settings_spec_get_type(),
    }
}

impl SettingsSpec {
    //#[doc(alias = "wp_settings_spec_check_value")]
    //pub fn check_value(&self, value: /*Ignored*/&SpaJson) -> bool {
    //    unsafe { TODO: call ffi:wp_settings_spec_check_value() }
    //}

    //#[doc(alias = "wp_settings_spec_get_default_value")]
    //#[doc(alias = "get_default_value")]
    //pub fn default_value(&self) -> /*Ignored*/Option<SpaJson> {
    //    unsafe { TODO: call ffi:wp_settings_spec_get_default_value() }
    //}

    #[doc(alias = "wp_settings_spec_get_description")]
    #[doc(alias = "get_description")]
    pub fn description(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::wp_settings_spec_get_description(self.to_glib_none().0))
        }
    }

    //#[doc(alias = "wp_settings_spec_get_max_value")]
    //#[doc(alias = "get_max_value")]
    //pub fn max_value(&self) -> /*Ignored*/Option<SpaJson> {
    //    unsafe { TODO: call ffi:wp_settings_spec_get_max_value() }
    //}

    //#[doc(alias = "wp_settings_spec_get_min_value")]
    //#[doc(alias = "get_min_value")]
    //pub fn min_value(&self) -> /*Ignored*/Option<SpaJson> {
    //    unsafe { TODO: call ffi:wp_settings_spec_get_min_value() }
    //}

    #[doc(alias = "wp_settings_spec_get_name")]
    #[doc(alias = "get_name")]
    pub fn name(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::wp_settings_spec_get_name(self.to_glib_none().0))
        }
    }

    #[doc(alias = "wp_settings_spec_get_value_type")]
    #[doc(alias = "get_value_type")]
    pub fn value_type(&self) -> SettingsSpecType {
        unsafe {
            from_glib(ffi::wp_settings_spec_get_value_type(self.to_glib_none().0))
        }
    }
}
