// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::{ffi,Core,Iterator,Object,SettingsSpec};
use glib::{prelude::*,translate::*};

glib::wrapper! {
    #[doc(alias = "WpSettings")]
    pub struct Settings(Object<ffi::WpSettings, ffi::WpSettingsClass>) @extends Object;

    match fn {
        type_ => || ffi::wp_settings_get_type(),
    }
}

impl Settings {
    #[doc(alias = "wp_settings_new")]
    pub fn new(core: &Core, metadata_name: Option<&str>) -> Settings {
        skip_assert_initialized!();
        unsafe {
            from_glib_full(ffi::wp_settings_new(core.to_glib_none().0, metadata_name.to_glib_none().0))
        }
    }

    #[doc(alias = "wp_settings_delete")]
    pub fn delete(&self, name: &str) -> bool {
        unsafe {
            from_glib(ffi::wp_settings_delete(self.to_glib_none().0, name.to_glib_none().0))
        }
    }

    #[doc(alias = "wp_settings_delete_all")]
    pub fn delete_all(&self) {
        unsafe {
            ffi::wp_settings_delete_all(self.to_glib_none().0);
        }
    }

    //#[doc(alias = "wp_settings_get")]
    //pub fn get(&self, name: &str) -> /*Ignored*/Option<SpaJson> {
    //    unsafe { TODO: call ffi:wp_settings_get() }
    //}

    //#[doc(alias = "wp_settings_get_saved")]
    //#[doc(alias = "get_saved")]
    //pub fn saved(&self, name: &str) -> /*Ignored*/Option<SpaJson> {
    //    unsafe { TODO: call ffi:wp_settings_get_saved() }
    //}

    #[doc(alias = "wp_settings_get_spec")]
    #[doc(alias = "get_spec")]
    pub fn spec(&self, name: &str) -> Option<SettingsSpec> {
        unsafe {
            from_glib_full(ffi::wp_settings_get_spec(self.to_glib_none().0, name.to_glib_none().0))
        }
    }

    #[doc(alias = "wp_settings_new_iterator")]
    pub fn new_iterator(&self) -> Option<Iterator> {
        unsafe {
            from_glib_full(ffi::wp_settings_new_iterator(self.to_glib_none().0))
        }
    }

    #[doc(alias = "wp_settings_reset")]
    pub fn reset(&self, name: &str) -> bool {
        unsafe {
            from_glib(ffi::wp_settings_reset(self.to_glib_none().0, name.to_glib_none().0))
        }
    }

    #[doc(alias = "wp_settings_reset_all")]
    pub fn reset_all(&self) {
        unsafe {
            ffi::wp_settings_reset_all(self.to_glib_none().0);
        }
    }

    #[doc(alias = "wp_settings_save")]
    pub fn save(&self, name: &str) -> bool {
        unsafe {
            from_glib(ffi::wp_settings_save(self.to_glib_none().0, name.to_glib_none().0))
        }
    }

    #[doc(alias = "wp_settings_save_all")]
    pub fn save_all(&self) {
        unsafe {
            ffi::wp_settings_save_all(self.to_glib_none().0);
        }
    }

    //#[doc(alias = "wp_settings_set")]
    //pub fn set(&self, name: &str, value: /*Ignored*/&SpaJson) -> bool {
    //    unsafe { TODO: call ffi:wp_settings_set() }
    //}

    //#[doc(alias = "wp_settings_subscribe")]
    //pub fn subscribe(&self, pattern: &str, callback: /*Unimplemented*/FnOnce(&Settings, &str, /*Ignored*/SpaJson), user_data: /*Unimplemented*/Option<Basic: Pointer>) -> /*Unimplemented*/Basic: UIntPtr {
    //    unsafe { TODO: call ffi:wp_settings_subscribe() }
    //}

    //#[doc(alias = "wp_settings_subscribe_closure")]
    //pub fn subscribe_closure(&self, pattern: &str, closure: Option<&glib::Closure>) -> /*Unimplemented*/Basic: UIntPtr {
    //    unsafe { TODO: call ffi:wp_settings_subscribe_closure() }
    //}

    //#[doc(alias = "wp_settings_unsubscribe")]
    //pub fn unsubscribe(&self, subscription_id: /*Unimplemented*/Basic: UIntPtr) -> bool {
    //    unsafe { TODO: call ffi:wp_settings_unsubscribe() }
    //}

    #[doc(alias = "metadata-name")]
    pub fn metadata_name(&self) -> Option<glib::GString> {
        ObjectExt::property(self, "metadata-name")
    }

    #[doc(alias = "wp_settings_find")]
    pub fn find(core: &Core, metadata_name: Option<&str>) -> Option<Settings> {
        skip_assert_initialized!();
        unsafe {
            from_glib_full(ffi::wp_settings_find(core.to_glib_none().0, metadata_name.to_glib_none().0))
        }
    }
}
