// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::{ffi};
use glib::{translate::*};

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct SettingsItem(Shared<ffi::WpSettingsItem>);

    match fn {
        ref => |ptr| ffi::wp_settings_item_ref(ptr),
        unref => |ptr| ffi::wp_settings_item_unref(ptr),
        type_ => || ffi::wp_settings_item_get_type(),
    }
}

impl SettingsItem {
    #[doc(alias = "wp_settings_item_get_key")]
    #[doc(alias = "get_key")]
    pub fn key(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::wp_settings_item_get_key(self.to_glib_none().0))
        }
    }

    //#[doc(alias = "wp_settings_item_get_value")]
    //#[doc(alias = "get_value")]
    //pub fn value(&self) -> /*Ignored*/Option<SpaJson> {
    //    unsafe { TODO: call ffi:wp_settings_item_get_value() }
    //}
}
