// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::{ffi,Object,SessionItem,SiAdapterPortsState};
use glib::{object::ObjectType as _,prelude::*,signal::{connect_raw, SignalHandlerId},translate::*};
use std::{boxed::Box as Box_};

glib::wrapper! {
    #[doc(alias = "WpSiAdapter")]
    pub struct SiAdapter(Interface<ffi::WpSiAdapter, ffi::WpSiAdapterInterface>) @requires SessionItem, Object;

    match fn {
        type_ => || ffi::wp_si_adapter_get_type(),
    }
}

impl SiAdapter {
        pub const NONE: Option<&'static SiAdapter> = None;
    
}

pub trait SiAdapterExt: IsA<SiAdapter> + 'static {
    //#[doc(alias = "wp_si_adapter_get_ports_format")]
    //#[doc(alias = "get_ports_format")]
    //fn ports_format(&self) -> (/*Ignored*/SpaPod, Option<glib::GString>) {
    //    unsafe { TODO: call ffi:wp_si_adapter_get_ports_format() }
    //}

    #[doc(alias = "wp_si_adapter_get_ports_state")]
    #[doc(alias = "get_ports_state")]
    fn ports_state(&self) -> SiAdapterPortsState {
        unsafe {
            from_glib(ffi::wp_si_adapter_get_ports_state(self.as_ref().to_glib_none().0))
        }
    }

    //#[doc(alias = "wp_si_adapter_set_ports_format")]
    //fn set_ports_format<P: FnOnce(Result<(), glib::Error>) + 'static>(&self, format: /*Ignored*/Option<SpaPod>, mode: Option<&str>, callback: P) {
    //    unsafe { TODO: call ffi:wp_si_adapter_set_ports_format() }
    //}

    //
    //fn set_ports_format_future(&self, format: /*Ignored*/Option<SpaPod>, mode: Option<&str>) -> Pin<Box_<dyn std::future::Future<Output = Result<(), glib::Error>> + 'static>> {

        //let format = format.map(ToOwned::to_owned);
        //let mode = mode.map(ToOwned::to_owned);
        //Box_::pin(gio::GioFuture::new(self, move |obj, cancellable, send| {
        //    obj.set_ports_format(
        //        format.as_ref().map(::std::borrow::Borrow::borrow),
        //        mode.as_ref().map(::std::borrow::Borrow::borrow),
        //        move |res| {
        //            send.resolve(res);
        //        },
        //    );
        //}))
    //}

    #[doc(alias = "adapter-ports-state-changed")]
    fn connect_adapter_ports_state_changed<F: Fn(&Self, SiAdapterPortsState, SiAdapterPortsState) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn adapter_ports_state_changed_trampoline<P: IsA<SiAdapter>, F: Fn(&P, SiAdapterPortsState, SiAdapterPortsState) + 'static>(this: *mut ffi::WpSiAdapter, object: ffi::WpSiAdapterPortsState, p0: ffi::WpSiAdapterPortsState, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(SiAdapter::from_glib_borrow(this).unsafe_cast_ref(), from_glib(object), from_glib(p0))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"adapter-ports-state-changed".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(adapter_ports_state_changed_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }
}

impl<O: IsA<SiAdapter>> SiAdapterExt for O {}
