// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::{ffi,Object,SessionItem};
use glib::{prelude::*,translate::*};

glib::wrapper! {
    #[doc(alias = "WpSiLinkable")]
    pub struct SiLinkable(Interface<ffi::WpSiLinkable, ffi::WpSiLinkableInterface>) @requires SessionItem, Object;

    match fn {
        type_ => || ffi::wp_si_linkable_get_type(),
    }
}

impl SiLinkable {
        pub const NONE: Option<&'static SiLinkable> = None;
    
}

pub trait SiLinkableExt: IsA<SiLinkable> + 'static {
    //#[doc(alias = "wp_si_linkable_get_acquisition")]
    //#[doc(alias = "get_acquisition")]
    //fn acquisition(&self) -> /*Ignored*/Option<SiAcquisition> {
    //    unsafe { TODO: call ffi:wp_si_linkable_get_acquisition() }
    //}

    #[doc(alias = "wp_si_linkable_get_ports")]
    #[doc(alias = "get_ports")]
    fn ports(&self, context: Option<&str>) -> Option<glib::Variant> {
        unsafe {
            from_glib_full(ffi::wp_si_linkable_get_ports(self.as_ref().to_glib_none().0, context.to_glib_none().0))
        }
    }
}

impl<O: IsA<SiLinkable>> SiLinkableExt for O {}
