[options]
library = "Wp"
version = "0.5"
min_cfg_version = "0.5"
target_path = "."
girs_directories = ["../gir-files/", "../"]
work_mode = "normal"
single_version_file = true
generate_safety_asserts = true
deprecate_by_min_version = true

generate = [
  "Wp.Core",
  "Wp.Properties",
  "Wp.Conf",
  "Wp.ObjectFeatures",
  # "Wp.SpaIdTable",
  # "Wp.SpaIdValue",
  "Wp.EventHook",
  "Wp.InterestEventHook",
  # "Wp.AsyncEventHook",
  "Wp.BaseDirsFlags",
  "Wp.PipewireObject",
  "Wp.Client",
  "Wp.GlobalProxy",
  "Wp.ComponentLoader",
  # "Wp.SpaJson",
  "Wp.ConstraintType",
  "Wp.ConstraintVerb",
  "Wp.ObjectManager",
  "Wp.Object",
  "Wp.CoreFeatures",
  "Wp.Device",
  "Wp.Direction",
  "Wp.Event",
  "Wp.EventDispatcher",
  "Wp.Iterator",
  "Wp.Factory",
  "Wp.FeatureActivationTransition",
  "Wp.Transition",
  # "Wp.Global",
  "Wp.Proxy",
  "Wp.ImplMetadata",
  # "Wp.Metadata",
  "Wp.ImplModule",
  "Wp.ImplNode",
  "Wp.InitFlags",
  "Wp.ObjectInterest",
  "Wp.InterestMatch",
  "Wp.InterestMatchFlags",
  # "Wp.IteratorMethods",
  "Wp.LibraryErrorEnum",
  "Wp.Link",
  "Wp.LinkState",
  "Wp.LogTopicFlags",
  # "Wp.LogTopic",
  "Wp.MetadataFeatures",
  "Wp.MetadataItem",
  "Wp.Node",
  "Wp.NodeState",
  "Wp.Port",
  "Wp.NodeFeatures",
  # "Wp.SpaPod",
  "Wp.Plugin",
  "Wp.PluginFeatures",
  "Wp.ProcInfo",
  "Wp.PropertiesItem",
  "Wp.ProxyFeatures",
  "Wp.SessionItem",
  "Wp.SessionItemFeatures",
  "Wp.Settings",
  "Wp.SettingsSpec",
  "Wp.SettingsFeatures",
  "Wp.SettingsItem",
  "Wp.SettingsSpecType",
  # "Wp.SiAcquisition",
  "Wp.SiLink",
  "Wp.SiLinkable",
  "Wp.SiAdapter",
  "Wp.SiAdapterPortsState",
  "Wp.SiFactory",
  # "Wp.SimpleEventHook",
  # "Wp.SpaDevice",
  # "Wp.SpaDeviceFeatures",
  # "Wp.SpaJsonBuilder",
  # "Wp.SpaJsonParser",
  # "Wp.SpaPodBuilder",
  # "Wp.SpaPodParser",
  "Wp.State",
  "Wp.TransitionStep",
]

manual = [
  "GLib.MainContext",
  "Gio.AsyncResult",
  "GLib.Error",
  "Gio.Cancellable",
  "Gio.AsyncReadyCallback",
  "GObject.Closure",
  "GLib.Variant",
  "GLib.EqualFunc",
  "GObject.Object",
  "GLib.Source",
  "GLib.SourceFunc",
  "GLib.DestroyNotify",
  "GObject.Value",
  "GLib.Quark",
]
